---
development:
  dialect: mariadb
  database: aquila_development
  user: aquila
  password: aquila
  host: 127.0.0.1
  pool: 5

test:
  dialect: sqlite3
  database: aquila_test.sqlite

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/aquila_server_production?sslmode=disable"}}
